import 'package:uuid/uuid.dart';

class Location {
  /// Maximum length for location names
  static const int maxNameLength = 100;

  final String id;
  final String name;
  final String initials;
  final double? latitude;
  final double? longitude;
  final DateTime createdAt;
  final DateTime updatedAt;

  Location({
    required this.id,
    required this.name,
    required this.initials,
    this.latitude,
    this.longitude,
    DateTime? createdAt,
    DateTime? updatedAt,
  })  : createdAt = createdAt ?? DateTime.now(),
        updatedAt = updatedAt ?? DateTime.now();

  /// Creates a new location with a generated UUID.
  /// The initials must be provided (generated by the controller).
  factory Location.create({
    required String name,
    required String initials,
    double? latitude,
    double? longitude,
  }) {
    return Location(
      id: const Uuid().v4(),
      name: name,
      initials: initials,
      latitude: latitude,
      longitude: longitude,
    );
  }

  Location copyWith({
    String? name,
    String? initials,
    double? latitude,
    double? longitude,
    bool clearLatitude = false,
    bool clearLongitude = false,
  }) {
    return Location(
      id: id,
      name: name ?? this.name,
      initials: initials ?? this.initials,
      latitude: clearLatitude ? null : (latitude ?? this.latitude),
      longitude: clearLongitude ? null : (longitude ?? this.longitude),
      createdAt: createdAt,
      updatedAt: DateTime.now(),
    );
  }

  /// Validates the location and returns a list of error messages.
  /// Returns an empty list if the location is valid.
  List<String> validate() {
    final errors = <String>[];

    if (name.trim().isEmpty) {
      errors.add('Name is required');
    }

    if (name.length > maxNameLength) {
      errors.add('Name is too long (maximum $maxNameLength characters)');
    }

    if (initials.isEmpty) {
      errors.add('Initials are required');
    }

    // GPS coordinates validation (if provided, both must be present)
    if ((latitude != null) != (longitude != null)) {
      errors.add('Both latitude and longitude must be provided together');
    }

    if (latitude != null && (latitude! < -90 || latitude! > 90)) {
      errors.add('Latitude must be between -90 and 90');
    }

    if (longitude != null && (longitude! < -180 || longitude! > 180)) {
      errors.add('Longitude must be between -180 and 180');
    }

    return errors;
  }

  /// Returns true if the location passes all validation rules.
  bool get isValid => validate().isEmpty;

  factory Location.fromMap(Map map) {
    if (map['id'] == null) {
      throw ArgumentError('id is required but was null');
    }
    if (map['name'] == null) {
      throw ArgumentError('name is required but was null');
    }
    if (map['initials'] == null) {
      throw ArgumentError('initials is required but was null');
    }

    return Location(
      id: map['id'] as String,
      name: map['name'] as String,
      initials: map['initials'] as String,
      latitude: map['latitude'] as double?,
      longitude: map['longitude'] as double?,
      createdAt:
          map['createdAt'] != null ? DateTime.parse(map['createdAt']) : null,
      updatedAt:
          map['updatedAt'] != null ? DateTime.parse(map['updatedAt']) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'initials': initials,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Location && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;
}
